version: '3'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.2
    container_name: elasticsearch
    environment:      
      - discovery.type=single-node    
    volumes:
      - ./data:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    
  web:
    build: .
    entrypoint: gunicorn -b 0.0.0.0:5000 ui.app:app
    volumes:
      - '.:/app'   
    ports:
      - '5000:5000'

  tor:
    image: dperson/torproxy
    volumes:
      - './conf/torrc:/etc/tor/torrc'
    ports:
      - '9050:9050'
      - '9051:9051'
  